remote_theme: piharpi/jekyll-klise
title: siedem nozy
description: siedem nozy
author:
  name: Michal Foerster

features                                  :

  - title                                 : GitHub Pages Jekyll Theme
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome_icon_name                 : magic
